# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-02 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_create_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dogage',
            field=models.CharField(max_length=1000),
        ),
    ]
