# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181002_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breedname', models.CharField(max_length=1000)),
                ('breedsize', models.CharField(max_length=1000)),
                ('friendliness', models.CharField(max_length=1000)),
                ('trainability', models.CharField(max_length=1000)),
                ('sheddingamount', models.CharField(max_length=1000)),
                ('exerciseneeds', models.CharField(max_length=1000)),
                ('requestor', models.GenericIPAddressField()),
            ],
        ),
    ]
