# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-04 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20181004_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='breedsize',
            field=models.IntegerField(choices=[('Tiny', 'Tiny'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')]),
        ),
    ]
