# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-04 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20181004_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dogage',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dog',
            name='dogbreed',
            field=models.CharField(max_length=1000),
        ),
    ]
