# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20181005_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='breedsize',
            field=models.CharField(max_length=1000),
        ),
    ]
