# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-02 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170905_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogname', models.CharField(max_length=1000)),
                ('dogage', models.DateTimeField()),
                ('dogbreed', models.CharField(max_length=1000)),
                ('doggender', models.CharField(max_length=1000)),
                ('dogcolor', models.CharField(max_length=1000)),
                ('dogfood', models.CharField(max_length=1000)),
                ('dogtoy', models.CharField(max_length=1000)),
                ('eventtype', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField()),
                ('userid', models.CharField(blank=True, max_length=1000)),
                ('requestor', models.GenericIPAddressField()),
            ],
        ),
    ]
