# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-02 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dog'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('age', models.DateTimeField()),
                ('password', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('gender', models.CharField(max_length=1000)),
                ('educationlevel', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=1000)),
            ],
        ),
    ]
