# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_breed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breed',
            name='requestor',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='eventtype',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='requestor',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='userid',
        ),
        migrations.AlterField(
            model_name='breed',
            name='breedsize',
            field=models.CharField(choices=[('Tiny', 'Tiny'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='breed',
            name='exerciseneeds',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='breed',
            name='friendliness',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='breed',
            name='sheddingamount',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='breed',
            name='trainability',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='dog',
            name='dogage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dog',
            name='dogbreed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Breed'),
        ),
    ]
