# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181005_0306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Create_User',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
